CREATE TYPE "aa"."resale_listing_status" AS ENUM('Bought', 'Sold');--> statement-breakpoint
CREATE TABLE "aa"."resale_listings" (
	"id" serial PRIMARY KEY NOT NULL,
	"hash_code" char(16) NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"listing_source" "aa"."listing_source" NOT NULL,
	"status" "aa"."resale_listing_status" NOT NULL,
	"make_and_model" varchar NOT NULL,
	"short_description" varchar NOT NULL,
	"full_description" varchar,
	"mileage" integer,
	"mileage_unit" varchar,
	"year" integer,
	"registration" varchar,
	"currency_symbol" char(1),
	"asking_price" integer,
	"vat_status" varchar,
	"location" varchar,
	"drive_configuration" varchar,
	"body_type" varchar,
	"cab_type" varchar,
	"fuel_type" varchar,
	"gearbox_type" varchar,
	"wheelbase" varchar,
	"engine_size" varchar,
	"colour" varchar,
	"seats" integer,
	"emission_class" varchar,
	"number_of_owners" integer,
	"service_history" varchar,
	"basic_history_check" varchar,
	"mot_status" varchar,
	"mot_expiry" date,
	"auction_closes" timestamp with time zone,
	"specs_and_features" varchar,
	"tax_status" varchar,
	"tax_due_date" date,
	"co2_emissions" integer,
	"marked_for_export" boolean,
	"date_of_last_v5c_issued" date,
	"month_of_first_registration" varchar,
	"type_approval" varchar,
	"revenue_weight" integer,
	"ai_sell_price_low" integer,
	"ai_sell_price_high" integer,
	"ads_price" integer,
	"eBayUrl" varchar NOT NULL,
	"facebookUrl" varchar NOT NULL,
	CONSTRAINT "resale_listings_hash_code_unique" UNIQUE("hash_code")
);
--> statement-breakpoint
CREATE INDEX "idx_resale_listings_hash_code" ON "aa"."resale_listings" USING btree ("hash_code" bpchar_ops);